### ISSUE TITLE
Failed to load hook function "../src/plugin_packages/ep_openid_connect:authenticate" for plugin "ep_openid_connect" part "main" hook set "hooks" hook "authenticate": TypeError: LRU is not a constructor

### ISSUE THREAD

**Issue by vladimirdulov** [ether/ep_openid_connect#113]
I get the following error in the etherpad-lite log, openid connect doesn't seem to work.

```
[2024-04-15T15:47:24.461] [ERROR] settings - Failed to load hook function "/run/etherpad-lite/src/plugin_packages/ep_openid_connect:authenticate" for plugin "ep_openid_connect" part "main" hook set "hooks" hook "authenticate": TypeError: LRU is not a constructor
    at Object.<anonymous> (/app/code/src/plugin_packages/openid-client/lib/helpers/request.js:62:16)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.S (/run/etherpad-lite/node_modules/.pnpm/tsx@4.7.2/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/app/code/src/plugin_packages/openid-client/lib/client.js:25:17)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.S (/run/etherpad-lite/node_modules/.pnpm/tsx@4.7.2/node_modules/tsx/dist/cjs/index.cjs:1:1292)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/app/code/src/plugin_packages/openid-client/lib/issuer.js:5:19)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
 ```

Ethepad-lite version: 2.0.2 (it seems all 2.0.x affected)

**Comment by TomNewChao** [comment]
I also encountered the same problem, is there any good way to solve it? @vladimirdulov

**Comment by vladimirdulov** [comment]
@TomNewChao There is a relevant discussion on this issue
https://github.com/ether/etherpad-lite/issues/6330

**Comment by yacchin1205** [comment]
The Issue https://github.com/ether/etherpad-lite/issues/6330 has been resolved, so this issue may be resolved as well. You can try it in the new release.

**Comment by JohnMcLear** [comment]
Upstream etherpad-lite#6330 was resolved, and the plugin has since been rewritten to use `@etherpad/node-openid-client` (see current index.js) — the `openid-client` package that threw "LRU is not a constructor" is no longer in the dependency tree. Closing as fixed.
