### ISSUE TITLE
[ERROR] server - Error occurred while starting Etherpad

### ISSUE THREAD

**Issue by tommyhlw** [ether/ep_openid_connect#6]
I cloned the latest repo https://github.com/ether/etherpad-lite.git
```
docker build . -t etherpadlite/etherpadlite
```
run container
```
docker run -p 9001:9001 etherpadlite/etherpadlite
```
then open bash of the docker
```
docker exec -it etherpad bash
```
installed openid plugin
```
npm i ep_openid_connect
```
adjusted settings.json accordingly
```
.....
 /*
   * This setting is used if you require authentication of all users.
   *
   * Note: "/admin" always requires authentication.
   */

 "ep_openid_connect": {
    "issuer": "https://myurl.de",
    "client_id": "XXXX",
    "client_secret": "XXX",
    "base_url": "http://myurl.de:9001"
},
  "requireAuthentication": "${REQUIRE_AUTHENTICATION:true}",
    .....
```

even tried with just:
```
  "requireAuthentication": true,
  ```

then exit container and create new image
```
docker commit CONTAINERID etherpad/oauth
```
run container
```
docker run -p 9001:9001 etherdpad/oauth
```
reullts in:
```
...
[2021-07-16 21:19:28.369] [INFO] plugins - Loading plugin ep_openid_connect...
[2021-07-16 21:19:28.371] [INFO] plugins - Loaded 2 plugins
[2021-07-16 21:19:28.817] [INFO] APIHandler - Api key file read from: "/opt/etherpad-lite/APIKEY.txt"
[2021-07-16 21:19:28.902] [INFO] server - Installed plugins: ep_openid_connect@2.0.7
[2021-07-16 21:19:29.077] [ERROR] server - Error occurred while starting Etherpad
```
with default setting.json it runs but of course without authentication :-(

The message is not telling much, pretty sure the syntax is fine, because syntax error in settings give a proper error message
Any Idea whats wrong? Is the latest git incompatible?

**Comment by rhansen** [comment]
Please [set the log level to debug](https://github.com/ether/etherpad-lite/blob/ca4cc2d7c00874c88b384ea5dcd55462513ab394/settings.json.docker#L580-L585) and paste the full output (radacted as necessary).

**Comment by tommyhlw** [comment]
```
....
[2021-07-18 18:24:21.759] [INFO] plugins - npm --version: 6.14.13
[2021-07-18 18:24:24.971] [DEBUG] runCmd - Command returned successfully: npm ls --long --json --depth=0 --no-production
[2021-07-18 18:24:24.978] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2021-07-18 18:24:24.978] [INFO] plugins - Loading plugin ep_openid_connect...
[2021-07-18 18:24:24.980] [INFO] plugins - Loaded 2 plugins
[2021-07-18 18:24:25.361] [DEBUG] AbsolutePaths - Relative path "./APIKEY.txt" can be rewritten to "/opt/etherpad-lite/APIKEY.txt"
[2021-07-18 18:24:25.361] [INFO] APIHandler - Api key file read from: "/opt/etherpad-lite/APIKEY.txt"
[2021-07-18 18:24:25.426] [DEBUG] server - Removing SIGINT listener because it might interfere with shutdown tasks. Function code:
() => terminateWorkersAndMaster()
Current stack:
    at removeSignalListener (/opt/etherpad-lite/src/node/server.js:81:36)
    at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:138:9)
    at process.emit (events.js:387:35)
    at process.emit (domain.js:470:12)
    at _addListener (events.js:418:14)
    at process.addListener (events.js:466:10)
    at initWorkerThreadsWorker (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:134:13)
    at selectWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:219:16)
    at Object.getWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:230:26)
    at Object.<anonymous> (/opt/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
[2021-07-18 18:24:25.427] [DEBUG] server - Removing SIGTERM listener because it might interfere with shutdown tasks. Function code:
() => terminateWorkersAndMaster()
Current stack:
    at removeSignalListener (/opt/etherpad-lite/src/node/server.js:81:36)
    at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:138:9)
    at process.emit (events.js:387:35)
    at process.emit (domain.js:470:12)
    at _addListener (events.js:418:14)
    at process.addListener (events.js:466:10)
    at initWorkerThreadsWorker (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:135:13)
    at selectWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:219:16)
    at Object.getWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:230:26)
    at Object.<anonymous> (/opt/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
[2021-07-18 18:24:25.441] [INFO] server - Installed plugins: ep_openid_connect@2.0.7
[2021-07-18 18:24:25.441] [DEBUG] server - Installed parts:
ep_openid_connect/ep_openid_connect
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/stats
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_etherpad-lite/Minify
ep_etherpad-lite/DB
[2021-07-18 18:24:25.452] [DEBUG] server - Installed server-side hooks:
  authenticate:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  authnFailure:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  clientVars:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  createServer:
    ep_etherpad-lite:
      express: ep_etherpad-lite/node/hooks/express
  expressCloseServer:
    ep_etherpad-lite:
      socketio: ep_etherpad-lite/node/hooks/express/socketio
  expressConfigure:
    ep_etherpad-lite:
      webaccess: ep_etherpad-lite/node/hooks/express/webaccess
  expressCreateServer:
    ep_etherpad-lite:
      admin: ep_etherpad-lite/node/hooks/express/admin
      adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
      adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
      apicalls: ep_etherpad-lite/node/hooks/express/apicalls
      errorhandling: ep_etherpad-lite/node/hooks/express/errorhandling
      i18n: ep_etherpad-lite/node/hooks/i18n
      importexport: ep_etherpad-lite/node/hooks/express/importexport
      openapi: ep_etherpad-lite/node/hooks/express/openapi
      padreadonly: ep_etherpad-lite/node/hooks/express/padreadonly
      padurlsanitize: ep_etherpad-lite/node/hooks/express/padurlsanitize
      socketio: ep_etherpad-lite/node/hooks/express/socketio
      specialpages: ep_etherpad-lite/node/hooks/express/specialpages
      static: ep_etherpad-lite/node/hooks/express/static
      tests: ep_etherpad-lite/node/hooks/express/tests
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  handleMessage:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  loadSettings:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  preAuthorize:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  restartServer:
    ep_etherpad-lite:
      express: ep_etherpad-lite/node/hooks/express
  shutdown:
    ep_etherpad-lite:
      DB: ep_etherpad-lite/node/db/DB
      express: ep_etherpad-lite/node/hooks/express
      Minify: ep_etherpad-lite/node/utils/Minify
      stats: ep_etherpad-lite/node/stats
  socketio:
    ep_etherpad-lite:
      adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
      adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
      socketio: ep_etherpad-lite/node/handler/PadMessageHandler
[2021-07-18 18:24:25.644] [ERROR] server - Error occurred while starting Etherpad
[2021-07-18 18:24:25.645] [DEBUG] server - unhandled rejection: TypeError: Cannot read property 'sockets' of undefined
    at Gauge._readFn (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:73:54)
    at Gauge.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/metrics/Gauge.js:24:17)
    at /opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:62:46
    at Array.forEach (<anonymous>)
    at Collection.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:60:32)
    at Object.exports.exit (/opt/etherpad-lite/src/node/server.js:221:75)
    at Object.exports.start (/opt/etherpad-lite/src/node/server.js:157:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-07-18 18:24:25.646] [DEBUG] server - uncaught exception: TypeError: Cannot read property 'sockets' of undefined
    at Gauge._readFn (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:73:54)
    at Gauge.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/metrics/Gauge.js:24:17)
    at /opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:62:46
    at Array.forEach (<anonymous>)
    at Collection.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:60:32)
    at Object.exports.exit (/opt/etherpad-lite/src/node/server.js:221:75)
    at Object.exports.start (/opt/etherpad-lite/src/node/server.js:157:26)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-07-18 18:24:25.647] [DEBUG] server - unhandled rejection: TypeError: Cannot read property 'sockets' of undefined
    at Gauge._readFn (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:73:54)
    at Gauge.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/metrics/Gauge.js:24:17)
    at /opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:62:46
    at Array.forEach (<anonymous>)
    at Collection.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:60:32)
    at Object.exports.exit (/opt/etherpad-lite/src/node/server.js:221:75)
    at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:117:15)
    at process.emit (events.js:375:28)
    at process.emit (domain.js:470:12)
    at process._fatalException (internal/process/execution.js:163:25)

```

the debug log repeats the following part over and over again:

```
[2021-07-18 18:24:25.647] [DEBUG] server - unhandled rejection: TypeError: Cannot read property 'sockets' of undefined
    at Gauge._readFn (/opt/etherpad-lite/src/node/handler/PadMessageHandler.js:73:54)
    at Gauge.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/metrics/Gauge.js:24:17)
    at /opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:62:46
    at Array.forEach (<anonymous>)
    at Collection.toJSON (/opt/etherpad-lite/src/node_modules/measured-core/lib/Collection.js:60:32)
    at Object.exports.exit (/opt/etherpad-lite/src/node/server.js:221:75)
    at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:117:15)
    at process.emit (events.js:375:28)
    at process.emit (domain.js:470:12)
    at process._fatalException (internal/process/execution.js:163:25)

```

**Comment by rhansen** [comment]
Please try ether/etherpad-lite#5121 and see if you get a more useful error message.

**Comment by tommyhlw** [comment]
hope I pulled the PR correctly:

```
[2021-07-19 18:56:22.598] [INFO] plugins - Loading plugin ep_etherpad-lite...
[2021-07-19 18:56:22.598] [INFO] plugins - Loading plugin ep_openid_connect...
[2021-07-19 18:56:22.600] [INFO] plugins - Loaded 2 plugins
[2021-07-19 18:56:22.991] [DEBUG] AbsolutePaths - Relative path "./APIKEY.txt" can be rewritten to "/opt/etherpad-lite/APIKEY.txt"
[2021-07-19 18:56:22.992] [INFO] APIHandler - Api key file read from: "/opt/etherpad-lite/APIKEY.txt"
[2021-07-19 18:56:23.060] [DEBUG] server - Removing SIGINT listener because it might interfere with shutdown tasks. Function code:
() => terminateWorkersAndMaster()
Current stack:
    at removeSignalListener (/opt/etherpad-lite/src/node/server.js:81:36)
    at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:138:9)
    at process.emit (events.js:387:35)
    at process.emit (domain.js:470:12)
    at _addListener (events.js:418:14)
    at process.addListener (events.js:466:10)
    at initWorkerThreadsWorker (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:134:13)
    at selectWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:219:16)
    at Object.getWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:230:26)
    at Object.<anonymous> (/opt/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
[2021-07-19 18:56:23.060] [DEBUG] server - Removing SIGTERM listener because it might interfere with shutdown tasks. Function code:
() => terminateWorkersAndMaster()
Current stack:
    at removeSignalListener (/opt/etherpad-lite/src/node/server.js:81:36)
    at process.<anonymous> (/opt/etherpad-lite/src/node/server.js:138:9)
    at process.emit (events.js:387:35)
    at process.emit (domain.js:470:12)
    at _addListener (events.js:418:14)
    at process.addListener (events.js:466:10)
    at initWorkerThreadsWorker (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:135:13)
    at selectWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:219:16)
    at Object.getWorkerImplementation (/opt/etherpad-lite/src/node_modules/threads/dist/master/implementation.node.js:230:26)
    at Object.<anonymous> (/opt/etherpad-lite/src/node_modules/threads/dist/master/index.js:13:39)
[2021-07-19 18:56:23.079] [INFO] server - Installed plugins: ep_openid_connect@2.0.7
[2021-07-19 18:56:23.079] [DEBUG] server - Installed parts:
ep_openid_connect/ep_openid_connect
ep_etherpad-lite/openapi
ep_etherpad-lite/adminsettings
ep_etherpad-lite/adminplugins
ep_etherpad-lite/admin
ep_etherpad-lite/tests
ep_etherpad-lite/socketio
ep_etherpad-lite/errorhandling
ep_etherpad-lite/importexport
ep_etherpad-lite/apicalls
ep_etherpad-lite/webaccess
ep_etherpad-lite/padreadonly
ep_etherpad-lite/padurlsanitize
ep_etherpad-lite/specialpages
ep_etherpad-lite/i18n
ep_etherpad-lite/stats
ep_etherpad-lite/static
ep_etherpad-lite/express
ep_etherpad-lite/Minify
ep_etherpad-lite/DB
[2021-07-19 18:56:23.094] [DEBUG] server - Installed server-side hooks:
  authenticate:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  authnFailure:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  clientVars:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  createServer:
    ep_etherpad-lite:
      express: ep_etherpad-lite/node/hooks/express
  expressCloseServer:
    ep_etherpad-lite:
      socketio: ep_etherpad-lite/node/hooks/express/socketio
  expressConfigure:
    ep_etherpad-lite:
      webaccess: ep_etherpad-lite/node/hooks/express/webaccess
  expressCreateServer:
    ep_etherpad-lite:
      admin: ep_etherpad-lite/node/hooks/express/admin
      adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
      adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
      apicalls: ep_etherpad-lite/node/hooks/express/apicalls
      errorhandling: ep_etherpad-lite/node/hooks/express/errorhandling
      i18n: ep_etherpad-lite/node/hooks/i18n
      importexport: ep_etherpad-lite/node/hooks/express/importexport
      openapi: ep_etherpad-lite/node/hooks/express/openapi
      padreadonly: ep_etherpad-lite/node/hooks/express/padreadonly
      padurlsanitize: ep_etherpad-lite/node/hooks/express/padurlsanitize
      socketio: ep_etherpad-lite/node/hooks/express/socketio
      specialpages: ep_etherpad-lite/node/hooks/express/specialpages
      static: ep_etherpad-lite/node/hooks/express/static
      tests: ep_etherpad-lite/node/hooks/express/tests
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  handleMessage:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  loadSettings:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  preAuthorize:
    ep_openid_connect:
      ep_openid_connect: ep_openid_connect
  restartServer:
    ep_etherpad-lite:
      express: ep_etherpad-lite/node/hooks/express
  shutdown:
    ep_etherpad-lite:
      DB: ep_etherpad-lite/node/db/DB
      express: ep_etherpad-lite/node/hooks/express
      Minify: ep_etherpad-lite/node/utils/Minify
      stats: ep_etherpad-lite/node/stats
  socketio:
    ep_etherpad-lite:
      adminplugins: ep_etherpad-lite/node/hooks/express/adminplugins
      adminsettings: ep_etherpad-lite/node/hooks/express/adminsettings
      socketio: ep_etherpad-lite/node/handler/PadMessageHandler
[2021-07-19 18:56:23.305] [ERROR] server - Error occurred while starting Etherpad
[2021-07-19 18:56:23.307] [ERROR] server - Metrics at time of fatal error:
{
  "httpStartTime": 0,
  "memoryUsage": 110850048,
  "memoryUsageHeap": 35418224,
  "ueberdb_lockAwaits": 0,
  "ueberdb_lockAcquires": 0,
  "ueberdb_lockReleases": 0,
  "ueberdb_reads": 0,
  "ueberdb_readsFailed": 0,
  "ueberdb_readsFinished": 0,
  "ueberdb_readsFromCache": 0,
  "ueberdb_readsFromDb": 0,
  "ueberdb_readsFromDbFailed": 0,
  "ueberdb_readsFromDbFinished": 0,
  "ueberdb_writes": 0,
  "ueberdb_writesFailed": 0,
  "ueberdb_writesFinished": 0,
  "ueberdb_writesObsoleted": 0,
  "ueberdb_writesToDb": 0,
  "ueberdb_writesToDbFailed": 0,
  "ueberdb_writesToDbFinished": 0,
  "ueberdb_writesToDbRetried": 0,
  "totalUsers": 0,
  "activePads": 0
}
[2021-07-19 18:56:23.308] [ERROR] server - AggregateError: Issuer.discover() failed.
    OPError: expected 200 OK, got: 404 Not Found
    OPError: expected 200 OK, got: 404 Not Found
    at Function.discover (/opt/etherpad-lite/node_modules/openid-client/lib/issuer.js:265:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.exports.loadSettings [as hook_fn] (/opt/etherpad-lite/node_modules/ep_openid_connect/index.js:31:21)
[2021-07-19 18:56:23.308] [INFO] server - Exiting...
[2021-07-19 18:56:23.308] [INFO] server - Waiting for Node.js to exit...
[2021-07-19 18:56:28.310] [ERROR] server - Something that should have been cleaned up during the shutdown hook (such as a timer, worker thread, or open connection) is preventing Node.js from exiting
[2021-07-19 18:56:28.311] [ERROR] server - Enable `dumpOnUncleanExit` setting to get a dump of objects preventing a clean exit
[2021-07-19 18:56:28.312] [ERROR] server - Forcing an unclean exit...

```

**Comment by rhansen** [comment]
> `OPError: expected 200 OK, got: 404 Not Found`

Looks like either your `issuer` URL is incorrect, or your OpenID Connect provider doesn't support [discovery](https://openid.net/specs/openid-connect-discovery-1_0.html). Do you get anything if you visit https://myurl.de/.well-known/openid-configuration (where https://myurl.de is your `issuer` URL)? Note that ep_openid_connect currently requires discovery.

**Comment by tommyhlw** [comment]
You are right:
{"message":"openid-configuration not supported"}

It's nextcloud21. Don't want to share the url here. 
I will have a look tomorrow if openid can be setup correctly with nextcloud. Just created OAuth2 credentials in the adminpanel.

However a prober error message would be cool :-)

**Comment by tommyhlw** [comment]
Here a quick feedback.
Tested locally with keycloak as openid-IdP and the authroization worked after is set the redirect url in keyclock client to http://localhost:9001/ep_openid_connect/callback

Like mentioned from @rhansen my mistake was just using nextcloud as IdP which does sadly not support openid discovery

I will close this issue and just make a request for prober error handling:
-show in LOG that openid-configuration was not found
-maybe start webserver anywhay with basic etherpad authentication

Another request would be that one user should always resume to his name and not create a replica user in the pad:
-I accessed the pad with several browsers in parallel, after authentication my username was created multiple times in the pad

**Comment by tommyhlw** [comment]
and thanks for the quick support
